### ISSUE TITLE
Add `ruff` and `black` into formal `lint` check

### ISSUE THREAD

**Issue by tgmachina** [LLNL/certipy#13]
Will work on this after https://github.com/LLNL/certipy/pull/9 merges

**Comment by minrk** [comment]
we're pretty happy [running ruff](https://github.com/jupyterhub/jupyterhub/blob/036dcb644c57511b3028fcc0c1fdacf445f1375c/.pre-commit-config.yaml#L16-L29) via [pre-commit](https://pre-commit.ci) in JupyterHub

**Comment by tgmachina** [comment]
Neat, I hadn't heard of `pre-commit` before. I am used to using [left hook](https://github.com/evilmartians/lefthook) for catching these kinds of things before they make it up to the repo. Looks like the same functionality is available via `pre-commit`. I'll try it out, thanks :)

**Comment by minrk** [comment]
Yeah, I think pre-commit is the equivalent in the Python community. I've set up lots of repos with it, if you want me to tackle that. Or if you'd rather do it to get to know the tools, go for it!
