### ISSUE TITLE
certipy install fails if building from tar.gz

### ISSUE THREAD

**Issue by varunsaxena** [LLNL/certipy#2]
certipy install fails if building from tar.gz

$ ./build/li-jupyterhub/venv/bin/pip3 install certipy==0.1.2 --no-binary :all:
Collecting certipy==0.1.2
  Using cached https://files.pythonhosted.org/packages/04/1e/340c66cddafdbbc378ff4ddd8659c633a162471645059fc5976b3aadf58b/certipy-0.1.2.tar.gz
    Complete output from command python setup.py egg_info:
    warning: pypandoc module not found, could not convert Markdown to RST
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-pmj2g9co/certipy/setup.py", line 79, in <module>
        long_description = read_md(f.read())
      File "/tmp/pip-install-pmj2g9co/certipy/setup.py", line 73, in <lambda>
        read_md = lambda f: open(f, 'r').read()
      File "/home/vasaxena/Projects/lijupyterhub_trunk/build/li-jupyterhub/venv/lib/python3.6/codecs.py", line 895, in open
        file = builtins.open(filename, mode, buffering)
    OSError: [Errno 36] File name too long: "# Certipy\n\nA simple python tool for creating certificate authorities and certificates on\nthe fly.\n\n## Introduction\n\nCertipy was made to simplify the certificate creation process. To that end,\nCertipy exposes methods for creating and managing certificate authorities,\ncertificates, signing and building trust bundles. Behind the scenes Certipy:\n\n* Manages records of all certificates it creates\n  * External certs can be imported and managed by Certipy\n  * Maintains signing hierarchy\n* Persists certificates to files with appropriate permissions\n\n## Usage\n\n### Command line\n\nCreating a certificate authority:\n\nCertipy defaults to writing certs and certipy.json into a folder called `out`\nin your current directory.\n\n```\n$ certipy foo\nFILES {'ca': '', 'cert': 'out/foo/foo.crt', 'key': 'out/foo/foo.key'}\nIS_CA True\nSERIAL 0\nSIGNEES None\nPARENT_CA\n```\n\nCreating and signing a key-cert pair:\n\n```\n$ certipy bar --ca-name foo\nFILES {'ca': 'out/foo/foo.crt', 'key': 'out/bar/bar.key', 'cert': 'out/bar/bar.crt'}\nIS_CA False\nSERIAL 0\nSIGNEES None\nPARENT_CA foo\n```\n\nRemoval:\n\n```\ncertipy --rm bar\nDeleted:\nFILES {'ca': 'out/foo/foo.crt', 'key': 'out/bar/bar.key', 'cert': 'out/bar/bar.crt'}\nIS_CA False\nSERIAL 0\nSIGNEES None\nPARENT_CA foo\n```\n\n### Code\n\nCreating a certificate authority:\n\n```\nfrom certipy import Certipy\n\ncertipy = Certipy(store_dir='/tmp')\ncertipy.create_ca('foo')\nrecord = certipy.get_record('foo')\n```\n\nCreating and signing a key-cert pair:\n\n```\ncertipy.create_signed_pair('bar', 'foo')\nrecord = certipy.get_record('bar')\n```\n\nCreating trust:\n\n```\ncertipy.create_ca_bundle('ca-bundle.crt')\n\n# or to trust specific certs only:\ncertipy.create_ca_bundle_for_names('ca-bundle.crt', ['bar'])\n```\n\nRemoval:\n\n```\nrecord = certipy.remove_files('bar')\n```\n\nRecords are dicts with the following structure:\n\n```\n{\n  'serial': 0,\n  'is_ca': true,\n  'parent_ca': 'ca_name',\n  'signees': {\n    'signee_name': 1\n  },\n  'files': {\n    'key': 'path/to/key.key',\n    'cert': 'path/to/cert.crt',\n    'ca': 'path/to/ca.crt',\n  }\n}\n```\n\nThe `signees` will be empty for non-CA certificates. The `signees` field\nis stored as a python `Counter`. These relationships are used to build trust\nbundles.\n\nInformation in Certipy is generally passed around as records which point to\nactual files. For most `_record` methods, there are generally equivalent\n`_file` methods that operate on files themselves. The former will only affect\nrecords in Certipy's store and the latter will affect both (something happens\nto the file, the record for it should change, too).\n\n### Release\n\nCertipy is released under BSD license. For more details see the LICENSE file.\n\nLLNL-CODE-754897\n"
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-pmj2g9co/certipy/

Can pypandoc dependency be explicitly included in setup.py?

**Comment by tgmachina** [comment]
Hi @varunsaxena, `setup.py` has a fallback when pypandoc is not available, but there was an issue with that fallback. Its corrected in `0.1.3`. I'm going to close this issue, but let me know if you run into anything else, thanks!
